### PR TITLE
Add example with offline regression report and gzip json persistor

### PR DESCRIPTION
**Pull request by kjanosz**
Example with a new persistor. 

Btw, is it possible to change `resultDir` in test code? I was trying to set in code custom path both for persistor and for `HTMLReport` but didn't find a way.

### CODE REVIEW

**Comment by axel22** [comment]
No, as far as I remember, this is not possible - `resultDir` can only be set as part of the top-level context (that is, through the command line).

**Comment by axel22** [comment]
LGTM

**Comment by kjanosz** [comment]
As for documentation, should I create a new dedicated page for persistors and link it to "Getting started" section?

**Comment by axel22** [comment]
Yes - would be good to add a new page called _Persistors_ to the _Getting started_ section. It should probably go after _Reporters_, or somewhere near.

**Comment by kjanosz** [comment]
@axel22: 
Found a way to change `Context` so it affects `HTMLReport`.
It can be done with:

```
for {
    _ <- dyn.currentContext.using(dyn.currentContext.value + (reports.resultDir -> "newPath"))
} {
  performance of "XYZ" ...
}
```

Should I create similar example with above solution?

**Comment by axel22** [comment]
Yep, that works, although that API was not meant to be used in client code.

**Pull request merged**
